"""employer_id

Revision ID: 13c72f82986d
Revises: b2963d885c86
Create Date: 2025-04-03 11:25:37.971365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c72f82986d'
down_revision = 'b2963d885c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_job_employer", 'user', ['employer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint("fk_job_employer", type_='foreignkey')
        batch_op.drop_column('employer_id')

    # ### end Alembic commands ###
