""" multiple users model

Revision ID: 2604cf85f223
Revises: fa595e400583
Create Date: 2025-03-27 20:02:26.069935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2604cf85f223'
down_revision = 'fa595e400583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('Awards_and_honors')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('JOB_SEEKER', 'EMPLOYER', 'ADMIN', name='userrole'), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('role')

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Awards_and_honors', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
