"""added test

Revision ID: 4872134a1b3a
Revises: d143f2514f98
Create Date: 2025-04-17 13:03:33.383866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4872134a1b3a'
down_revision = 'd143f2514f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_interview_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=255), nullable=False),
    sa.Column('option_b', sa.String(length=255), nullable=False),
    sa.Column('option_c', sa.String(length=255), nullable=False),
    sa.Column('option_d', sa.String(length=255), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=300), nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=150), nullable=False),
    sa.Column('option_b', sa.VARCHAR(length=150), nullable=False),
    sa.Column('option_c', sa.VARCHAR(length=150), nullable=False),
    sa.Column('option_d', sa.VARCHAR(length=150), nullable=False),
    sa.Column('correct_option', sa.VARCHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pre_interview_test')
    # ### end Alembic commands ###
