"""added test

Revision ID: d143f2514f98
Revises: 55a81e50ff78
Create Date: 2025-04-17 12:50:28.960035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd143f2514f98'
down_revision = '55a81e50ff78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('option_a', sa.String(length=150), nullable=False),
    sa.Column('option_b', sa.String(length=150), nullable=False),
    sa.Column('option_c', sa.String(length=150), nullable=False),
    sa.Column('option_d', sa.String(length=150), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_test')
    # ### end Alembic commands ###
