"""resume

Revision ID: ecaf5aba5690
Revises: 533e9bb32f29
Create Date: 2025-02-28 08:43:08.639108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecaf5aba5690'
down_revision = '533e9bb32f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_year', sa.String(length=50), nullable=False),
    sa.Column('end_year', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('activities_interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_skills', sa.Text(), nullable=True))
        batch_op.drop_column('education')
        batch_op.drop_column('Awards_and_honors')
        batch_op.drop_column('skills')
        batch_op.drop_column('experience')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('skills', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('Awards_and_honors', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.TEXT(), nullable=False))
        batch_op.drop_column('key_skills')
        batch_op.drop_column('activities_interests')
        batch_op.drop_column('profile_summary')

    op.drop_table('work_experience')
    op.drop_table('education')
    # ### end Alembic commands ###
