"""award and honour

Revision ID: fa595e400583
Revises: ecaf5aba5690
Create Date: 2025-03-05 00:25:33.763254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa595e400583'
down_revision = 'ecaf5aba5690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Awards_and_honors', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('Awards_and_honors')

    # ### end Alembic commands ###
